force-app/main/default/objects/Administrator__c/Administrator__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Administrator</label>
</CustomObject>

force-app/main/default/objects/Log__c/Log__c.object-meta.xml
<CustomObject>
    <label>Log</label>
    <nameField>
        <displayFormat>#{0000000000}</displayFormat>
        <label>Log Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Log__c/fields/CPU_Time__c.field-meta.xml
<CustomField>
    <fullName>CPU_Time__c</fullName>
    <label>CPU Time (ms)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/DML_Rows__c.field-meta.xml
<CustomField>
    <fullName>DML_Rows__c</fullName>
    <label>DML Rows</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/Queries__c.field-meta.xml
<CustomField>
    <fullName>Queries__c</fullName>
    <label>Queries</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Log__c/recordTypes/ERROR.recordType-meta.xml
<RecordType>
    <fullName>ERROR</fullName>
    <active>true</active>
    <label>ERROR</label>
</RecordType>

force-app/main/default/classes/LoggerUtil.cls
public with sharing class LoggerUtil {

    public static List<String> getAddressList() {
        List<String> addressList = new list<String>();
        for(Administrator__c admin : Administrator__c.getall().values()) {
            addressList.add(admin.Email__c);
        }
        return addressList;    
    }

    public static Log__c createLog(Logger.LogParameter logParameter) {
        Log__c log = new Log__c();
        if (Schema.getGlobalDescribe().get(LoggerConstants.OBJECT_LOG).getDescribe().getRecordTypeInfosByName().get(logParameter.type) != null) {
            log.RecordTypeId = Schema.getGlobalDescribe().get(LoggerConstants.OBJECT_LOG).getDescribe().getRecordTypeInfosByName().get(logParameter.type).getRecordTypeId();
        }
        log.Queries__c = Limits.getQueries();
        log.DML_Statements__c = Limits.getDmlRows();
        log.DML_Rows__c = Limits.getDmlStatements();
        log.CPU_Time__c = Limits.getCpuTime();
        return log;
    }

    public static Messaging.SingleEmailMessage createEmail(Logger.LogParameter logParameter, List<String> addressList) {
        Messaging.SingleEmailMessage email = new Messaging.SingleEmailMessage();
        email.setSubject('Error in ' + logParameter.source);
        email.setPlainTextBody(logParameter.content);
        email.setToAddresses(addressList);
        return email;
    }

    public static Logger_Setting__mdt getLoggerConfiguration() {
        return Logger_Setting__mdt.getInstance(LoggerConstants.GLOBAL_SETTING);
    }

}