force-app/main/default/objects/Log__c/Log__c.object-meta.xml
<CustomObject>
    <label>Log</label>
    <nameField>
        <displayFormat>#{0000000000}</displayFormat>
        <label>Log Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Logger_Setting__mdt/fields/Send_Debug_Log_Emails__c.field-meta.xml
<CustomField>
    <fullName>Send_Debug_Log_Emails__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Send Debug Log Emails</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Logger_Setting__mdt/fields/Send_Error_Log_Emails__c.field-meta.xml
<CustomField>
    <fullName>Send_Error_Log_Emails__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Send Error Log Emails</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Logger_Setting__mdt/fields/Send_Execution_Log_Emails__c.field-meta.xml
<CustomField>
    <fullName>Send_Execution_Log_Emails__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Send Execution Log Emails</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Logger_Setting__mdt/fields/Send_Warning_Log_Emails__c.field-meta.xml
<CustomField>
    <fullName>Send_Warning_Log_Emails__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Send Warning Log Emails</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/LogTriggerHandler.cls
public with sharing class LogTriggerHandler {

    private static final Logger_Setting__mdt LOGGER_SETTING = LoggerUtil.getLoggerSetting();

    public static void handleAfterInsert(Map<Id, Log__c> logMap) {

        Set<Id> logIdForEmailSet = new Set<Id>();

        for (Log__c log : logMap.values()) {
            if (LOGGER_SETTING.Send_Error_Log_Emails__c && log.RecordType.Name == LoggerConstants.RECORD_TYPE_LABEL_ERROR_LOG
            || LOGGER_SETTING.Send_Warning_Log_Emails__c && log.RecordType.Name == LoggerConstants.RECORD_TYPE_LABEL_WARNING_LOG
            || LOGGER_SETTING.Send_Execution_Log_Emails__c && log.RecordType.Name == LoggerConstants.RECORD_TYPE_LABEL_EXECUTION_LOG
            || LOGGER_SETTING.Send_Debug_Log_Emails__c && log.RecordType.Name == LoggerConstants.RECORD_TYPE_LABEL_DEBUG_LOG) {
                logIdForEmailSet.add(log.Id);
            }
        }    

        if (!logIdForEmailSet.isEmpty()) {
            LoggerUtil.sendLogEmails(logIdForEmailSet);   
        }

    }

}