force-app/main/default/objects/Log__c/Log__c.object-meta.xml
<CustomObject>
    <label>Log</label>
    <nameField>
        <displayFormat>#{0000000000}</displayFormat>
        <label>Log Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Log__c/recordTypes/DEBUG.recordType-meta.xml
<RecordType>
    <fullName>DEBUG</fullName>
    <active>true</active>
    <label>DEBUG</label>
</RecordType>

force-app/main/default/objects/Log__c/recordTypes/ERROR.recordType-meta.xml
<RecordType>
    <fullName>ERROR</fullName>
    <active>true</active>
    <label>ERROR</label>
</RecordType>

force-app/main/default/objects/Log__c/recordTypes/INFO.recordType-meta.xml
<RecordType>
    <fullName>INFO</fullName>
    <active>true</active>
    <label>INFO</label>
</RecordType>

force-app/main/default/objects/Log__c/recordTypes/WARN.recordType-meta.xml
<RecordType>
    <fullName>WARN</fullName>
    <active>true</active>
    <label>WARN</label>
</RecordType>

force-app/main/default/objects/Logger_Configuration__c/Logger_Configuration__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Logger Configuration</label>
</CustomObject>

force-app/main/default/objects/Logger_Configuration__c/fields/Asynchronous_Mode__c.field-meta.xml
<CustomField>
    <fullName>Asynchronous_Mode__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If Log Record Inserting is active, all records are inserted through a Queueable job outside of the scope of the original transaction.</description>
    <inlineHelpText>If Log Record Inserting is active, all records are inserted through a Queueable job outside of the scope of the original transaction.</inlineHelpText>
    <label>Asynchronous Mode</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Logger_Configuration__c/fields/Event_Based_Logging__c.field-meta.xml
<CustomField>
    <fullName>Event_Based_Logging__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Event Based Logging</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Logger_Configuration__c/fields/Highest_Log_Level_for_Insert__c.field-meta.xml
<CustomField>
    <fullName>Highest_Log_Level_for_Insert__c</fullName>
    <defaultValue>&apos;INFO&apos;</defaultValue>
    <description>If Log Record Inserting is active, only logs with lower or equal levels to this are inserted.</description>
    <inlineHelpText>If Log Record Inserting is active, only logs with lower or equal levels to this are inserted.
Enter one of the values from below (listed from lowest to the highest):
ERROR
WARN
INFO
DEBUG
FINE
FINER
FINEST</inlineHelpText>
    <label>Highest Log Level for Insert</label>
    <length>32</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Logger_Configuration__c/fields/Log_Inserting_Active__c.field-meta.xml
<CustomField>
    <fullName>Log_Inserting_Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If set to true, log records with logging level lower or equal to the value of &quot;Highest Log Level for Insert&quot; are inserted into the database with detailed information.</description>
    <inlineHelpText>If set to true, log records with logging level lower or equal to the value of &quot;Highest Log Level for Insert&quot; are inserted into the database with detailed information.</inlineHelpText>
    <label>Log Inserting Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/ApexLoggerTest.cls
@IsTest
public class ApexLoggerTest {
    
    @TestSetup
    private static void createCustomSetting() {
        Logger_Configuration__c config = new Logger_Configuration__c();
        config.Log_Inserting_Active__c = true;
        config.Asynchronous_Mode__c = false;
        config.Highest_Log_Level_for_Insert__c = String.valueOf(LoggingLevel.DEBUG);
        config.Event_Based_Logging__c = true;
        insert config;
    }
    
    private static ApexLogger logger = ApexLogger.getLogger(ApexLoggerTest.class);
    
    @IsTest
    public static void testAsynchronousLog() {
        logger.config.Asynchronous_Mode__c = true;
        Test.startTest();
        logger.log('Default Log');
        Test.stopTest();
    }
    
    @IsTest
    public static void testMissingConfiguration() {
        logger.config = null;
        Test.startTest();
        logger.log('Default Log');
        logger.log('Default Log', 1);
        logger.error(new DMLException());
        Test.stopTest();
    }

    @IsTest
    public static void testGenerateAndInsertLogRecord() {
        Test.startTest();
        logger.generateAndInsertLogRecord(LoggingLevel.INFO, 'Info log');
        Test.stopTest();
    }

    @IsTest
    public static void testInsertLogRecordWithEvent() {
        Log__c log = new Log__c();
        log.Message__c = 'Test message';
        log.Data__c = 'Test data';
        log.Quiddity__c = 'AURA';

        Test.startTest();
        logger.insertLogRecord(log);
        Test.stopTest();
    }

    @IsTest
    public static void testIsInsertEnabledForLogLevel() {
        logger.config = null;
        Exception caughtException;

        Test.startTest();
        try {
            logger.isInsertEnabledForLogLevel(LoggingLevel.FINEST);
        } catch (Exception e) {
            caughtException = e;
        }
        Test.stopTest();
        
        System.assert(caughtException instanceof ApexLogger.InvalidLoggerConfigurationException);
    }

    @IsTest
    public static void testinvalidData() {
        Test.startTest();
        logger.log('Default Log', null);
        Test.stopTest();
    }
    
    @IsTest
    public static void testLoggerInitialization() {
        logger = new ApexLogger();
        Test.startTest();
        logger = ApexLogger.getLogger('Test Logger');
        Test.stopTest();
    }
    
    @IsTest
    public static void testDefaultLog() {
        Test.startTest();
        logger.log('Default Log');
        logger.log('Default Log', 1);
        Test.stopTest();
    }
    
    @IsTest
    public static void testErrorLog() {
        Test.startTest();
        logger.error('Error Log');
        logger.error('Error Log', 1);
        Test.stopTest();
    }
    
    @IsTest
    public static void testExceptionLog() {
        Test.startTest();
        logger.error(new DMLException('Exception Log'));
        Test.stopTest();
    }
    
    @IsTest
    public static void testWarnLog() {
        Test.startTest();
        logger.warn('Warn Log');
        logger.warn('Warn Log', 1);
        Test.stopTest();
    }
    
    @IsTest
    public static void testInfoLog() {
        Test.startTest();
        logger.info('Info Log');
        logger.info('Info Log', 1);
        Test.stopTest();
    }
    
    @IsTest
    public static void testEnteringLog() {
        Test.startTest();
        logger.entering();
        Test.stopTest();
    }
    
    @IsTest
    public static void testExitingLog() {
        Test.startTest();
        logger.exiting();
        Test.stopTest();
    }
    
    @IsTest
    public static void testDebugLog() {
        Test.startTest();
        logger.debug('Debug Log');
        logger.debug('Debug Log', 1);
        Test.stopTest();
    }
    
    @IsTest
    public static void testFineLog() {
        Test.startTest();
        logger.fine('Fine Log');
        logger.fine('Fine Log', 1);
        Test.stopTest();
    }
    
    @IsTest
    public static void testFinerLog() {
        Test.startTest();
        logger.finer('Finer Log');
        logger.finer('Finer Log', 1);
        Test.stopTest();
    }
    
    @IsTest
    public static void testFinestLog() {
        Test.startTest();
        logger.finest('Finest Log');
        logger.finest('Finest Log', 1);
        Test.stopTest();
    }
}